# Generated by Django 5.1.2 on 2024-11-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.IntegerField()),
                ('link', models.FilePathField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialDeEstudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeracao', models.IntegerField()),
                ('titulo', models.CharField(max_length=200)),
                ('valorXp', models.IntegerField()),
                ('texto', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.IntegerField()),
                ('texto', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Quizzes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SecaoDeEstudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeracao', models.IntegerField()),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=500)),
                ('valorXp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('senha', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=200)),
                ('curso', models.CharField(max_length=200)),
                ('periodo', models.IntegerField()),
                ('xp', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='planodeestudo',
            name='completo',
        ),
        migrations.AddField(
            model_name='planodeestudo',
            name='avaliacao',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='planodeestudo',
            name='data',
            field=models.DateField(auto_now=True, max_length=10),
        ),
        migrations.AddField(
            model_name='planodeestudo',
            name='descricao',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='planodeestudo',
            name='identificacao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planodeestudo',
            name='visibilidade',
            field=models.CharField(default='Restrito', max_length=50),
        ),
        migrations.AlterField(
            model_name='planodeestudo',
            name='titulo',
            field=models.CharField(default='Novo Plano de Estudo', max_length=200),
        ),
    ]
