# Generated by Django 5.1.2 on 2024-11-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0002_arquivo_categoria_materialdeestudo_pergunta_quizzes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planodeestudo',
            name='identificacao',
            field=models.IntegerField(),
        ),
    ]
