# Generated by Django 5.1.2 on 2024-11-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0004_alter_planodeestudo_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planodeestudo',
            name='visibilidade',
            field=models.CharField(max_length=50),
        ),
    ]
