# Generated by Django 5.1.2 on 2024-11-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0005_alter_planodeestudo_visibilidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planodeestudo',
            name='data',
            field=models.DateField(max_length=10),
        ),
    ]
