# Generated by Django 5.1.2 on 2024-11-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0006_alter_planodeestudo_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planodeestudo',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
