# Generated by Django 5.1.2 on 2024-11-27 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0007_alter_planodeestudo_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planodeestudo',
            name='avaliacao',
            field=models.FloatField(),
        ),
    ]
