# Generated by Django 5.1.2 on 2024-11-27 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0008_alter_planodeestudo_avaliacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.IntegerField()),
                ('texto', models.CharField(max_length=500)),
            ],
        ),
    ]
