# Generated by Django 5.1.2 on 2024-11-27 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0009_resposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='planodeestudo',
            name='nFavoritos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planodeestudo',
            name='nVisualizacoes',
            field=models.IntegerField(default=0),
        ),
    ]
