# Generated by Django 5.1.2 on 2024-12-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0010_planodeestudo_nfavoritos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planodeestudo',
            name='visibilidade',
            field=models.IntegerField(default=0),
        ),
    ]
